FROM python:3.10.7-slim-buster

WORKDIR /usr/src/app_web

RUN pip install --upgrade pip
COPY . /usr/src/app_web/
RUN pip3 install -r requirements.txt
EXPOSE 5000


CMD ["flask", "run", "--host", "0.0.0.0"]